# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234c3f48dfa97d69fe974215c6ee6f13b477c7091839dca78147e1405b2e1f86e382d5c4e8a786992d107f9e52ae312838f86bd2e1e292aba46d2f03067ee210

test:
  secret_key_base: 910c3d02f6b99b4481a9004db4882ebad1108fa406a3638addda1dad652141aa84ce3ae48a3544ac7bf58abeac78975fbb00cb4ef1cf7702c1e1cbf22238c3e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
